rules:
  - id: python-no-print-use-logger
    languages:
      - python
    message: "Evite usar print(). Utilize logging/logger para registrar mensagens da aplicação."
    severity: WARNING
    pattern: print(...)
    metadata:
      category: best-practice
      technology:
        - python
