name: SAST

on:
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps: 
      - uses: actions/checkout@v6

      - run: semgrep logout & semgrep ci --config semgrep-rules/no-print.yaml
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  fossa:
    name: fossa
    runs-on: ubuntu-latest
    needs: semgrep

    steps:
      - uses: actions/checkout@v4
      - uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
